export enum ActionType {
  CATEGORIES_GET = "getCategories",
  CATEGORIES_GET_SUCCESS = "getCategoriesSuccess",
  CATEGORIES_GET_ERROR = "getCategoriesError",
  CATEGORY_CREATE_INIT = "categoryCreateInit",
  CATEGORY_CREATE_SUCCESS = "categoryCreateSuccess",
  CATEGORY_CREATE_FAILED = "categoryCreateFailed",
  CATEGORY_DELETE_INIT = "categoryDeleteInit",
  CATEGORY_DELETE_SUCCESS = "categoryDeleteSuccess",
  CATEGORY_DELETE_FAILED = "categoryDeleteFailed",
  BLOG_CREATE_INIT = "blogCreateInit",
  BLOG_CREATE_SUCCESS = "blogCreateSuccess",
  BLOG_CREATE_FAILED = "blogCreateFailed",
  BLOG_LIST_INIT = "blogListInit",
  BLOG_LIST_SUCCESS = "blogListSuccess",
  BLOG_LIST_FAILED = "blogListFailed",
  BLOG_GET_INIT = "blogGetInit",
  BLOG_GET_SUCCESS = "blogGetSuccess",
  BLOG_GET_FAILED = "blogGetFailed",
  BLOG_UPDATE_INIT = "blogUpdateInit",
  BLOG_UPDATE_SUCCESS = "blogUpdateSuccess",
  BLOG_UPDATE_FAILED = "blogUpdateFailed",
}
